version: "3.9"

services:  
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwe"
    ports:
      - "5434:5432"
  microservice-for-working-with-user-balance:
    build: "."
    depends_on:
      - "postgres"
    ports:
      - "8080"